### ISSUE TITLE
scrum-dice 가 AWS 에 auto deploy 된다 (CD)

### ISSUE THREAD

**Issue by JeongJaeSoon** [2P3S/scrum-dice#1]
## Todo

- [x] Branch 는 main, develop
    - main : Live server
    - develop : Test server
- [x] Repository 에 branch protect 를 설정
- [x] Dockeffile 을 추가
    - README.md 에 사용방법 작성
- [ ] develop 브랜치에 merge 되면, 자동으로 EC2 서버에 반영 
    - EC2 서버 설정
    - appspec.yml
    - deploy.sh

**Comment by JeongJaeSoon** [comment]
https://github.com/2P3S/scrum-dice/pull/2

**Comment by JeongJaeSoon** [comment]
### EC2 에 Manual Deploy 

```bash
[ec2-user@ip-172-31-0-125 scrum-dice]$ docker run --env-file=.env --rm --name scrum-dice -p 80:3000 -d scrum-dice
9965954a4e4b54baf35b8c717d1f7b492279cff5991e3438721a5c7335709a78
[ec2-user@ip-172-31-0-125 scrum-dice]$ docker ps
CONTAINER ID   IMAGE        COMMAND                  CREATED              STATUS              PORTS                                   NAMES
9965954a4e4b   scrum-dice   "/nodejs/bin/node ./…"   About a minute ago   Up About a minute   0.0.0.0:80->3000/tcp, :::80->3000/tcp   scrum-dice
[ec2-user@ip-172-31-0-125 scrum-dice]$ curl localhost
<!DOCTYPE html><html lang="kr"><head><meta charSet="utf-8"/><title>Create Next App</title><meta name="description" content="Generated by create next app"/><meta name="viewport" content="width=device-width, initial-scale=1"/><link rel="icon" href="/favicon.ico"/><meta name="next-head-count" content="5"/><link rel="preload" href="/_next/static/media/7b53eb385565b6db-s.p.woff2" as="font" type="font/woff2" crossorigin="anonymous" data-next-font="size-adjust"/><link rel="preload" href="/_next/static/media/28777f2d837b799c-s.p.woff2" as="font" type="font/woff2" crossorigin="anonymous" data-next-font="size-adjust"/><link rel="preload" href="/_next/static/media/400b60eed27dfb33-s.p.woff2" as="font" type="font/woff2" crossorigin="anonymous" data-next-font="size-adjust"/><link rel="preload" href="/_next/static/media/7bb39e817a36d930-s.p.woff2" as="font" type="font/woff2" crossorigin="anonymous" data-next-font="size-adjust"/><link rel="preload" href="/_next/static/css/3ad7adcd6ac0cdb4.css" as="style"/><link rel="stylesheet" href="/_next/static/css/3ad7adcd6ac0cdb4.css" data-n-g=""/><link rel="preload" href="/_next/static/css/cbe848909a7e60de.css" as="style"/><link rel="stylesheet" href="/_next/static/css/cbe848909a7e60de.css" data-n-p=""/><link rel="preload" href="/_next/static/css/268f21f1b6a953c1.css" as="style"/><link rel="stylesheet" href="/_next/static/css/268f21f1b6a953c1.css" data-n-p=""/><noscript data-n-css=""></noscript><script defer="" nomodule="" src="/_next/static/chunks/polyfills-c67a75d1b6f99dc8.js"></script><script src="/_next/static/chunks/webpack-0c2b03d183be1d16.js" defer=""></script><script src="/_next/static/chunks/framework-ac88a2a245aea9ab.js" defer=""></script><script src="/_next/static/chunks/main-dd3f6ca723899de0.js" defer=""></script><script src="/_next/static/chunks/pages/_app-5badd0c9e455f14e.js" defer=""></script><script src="/_next/static/chunks/pages/index-cee06aa099f65162.js" defer=""></script><script src="/_next/static/eiYdyuiKcLG61JcBiroKt/_buildManifest.js" defer=""></script><script src="/_next/static/eiYdyuiKcLG61JcBiroKt/_ssgManifest.js" defer=""></script></head><body><div id="__next"><main class="__className_a1b27a __variable_9ec5dd"><h3 class="text-3xl">다국어 폰트 테스트</h3><button type="button" class="btn">한국어 폰트 테스트</button><button type="button" class="font-lato btn">english font test</button><h3 class="text-3xl">숫자 폰트 테스트</h3><button type="button" class="text-lg btn">123</button><button type="button" class="text-lg font-lato btn">123</button></main></div><script id="__NEXT_DATA__" type="application/json">{"props":{"pageProps":{}},"page":"/","query":{},"buildId":"eiYdyuiKcLG61JcBiroKt","nextExport":true,"autoExport":true,"isFallback":false,"scriptLoader":[]}</script></body></html>
```

### Local 에서 접속
* http://3.104.74.77/
```bash
# 94soon @ Soons-MacBookPro in ~/.ssh [2:25:09]
$ curl 'http://3.104.74.77/'
<!DOCTYPE html><html lang="kr"><head><meta charSet="utf-8"/><title>Create Next App</title><meta name="description" content="Generated by create next app"/><meta name="viewport" content="width=device-width, initial-scale=1"/><link rel="icon" href="/favicon.ico"/><meta name="next-head-count" content="5"/><link rel="preload" href="/_next/static/media/7b53eb385565b6db-s.p.woff2" as="font" type="font/woff2" crossorigin="anonymous" data-next-font="size-adjust"/><link rel="preload" href="/_next/static/media/28777f2d837b799c-s.p.woff2" as="font" type="font/woff2" crossorigin="anonymous" data-next-font="size-adjust"/><link rel="preload" href="/_next/static/media/400b60eed27dfb33-s.p.woff2" as="font" type="font/woff2" crossorigin="anonymous" data-next-font="size-adjust"/><link rel="preload" href="/_next/static/media/7bb39e817a36d930-s.p.woff2" as="font" type="font/woff2" crossorigin="anonymous" data-next-font="size-adjust"/><link rel="preload" href="/_next/static/css/3ad7adcd6ac0cdb4.css" as="style"/><link rel="stylesheet" href="/_next/static/css/3ad7adcd6ac0cdb4.css" data-n-g=""/><link rel="preload" href="/_next/static/css/cbe848909a7e60de.css" as="style"/><link rel="stylesheet" href="/_next/static/css/cbe848909a7e60de.css" data-n-p=""/><link rel="preload" href="/_next/static/css/268f21f1b6a953c1.css" as="style"/><link rel="stylesheet" href="/_next/static/css/268f21f1b6a953c1.css" data-n-p=""/><noscript data-n-css=""></noscript><script defer="" nomodule="" src="/_next/static/chunks/polyfills-c67a75d1b6f99dc8.js"></script><script src="/_next/static/chunks/webpack-0c2b03d183be1d16.js" defer=""></script><script src="/_next/static/chunks/framework-ac88a2a245aea9ab.js" defer=""></script><script src="/_next/static/chunks/main-dd3f6ca723899de0.js" defer=""></script><script src="/_next/static/chunks/pages/_app-5badd0c9e455f14e.js" defer=""></script><script src="/_next/static/chunks/pages/index-cee06aa099f65162.js" defer=""></script><script src="/_next/static/eiYdyuiKcLG61JcBiroKt/_buildManifest.js" defer=""></script><script src="/_next/static/eiYdyuiKcLG61JcBiroKt/_ssgManifest.js" defer=""></script></head><body><div id="__next"><main class="__className_a1b27a __variable_9ec5dd"><h3 class="text-3xl">다국어 폰트 테스트</h3><button type="button" class="btn">한국어 폰트 테스트</button><button type="button" class="font-lato btn">english font test</button><h3 class="text-3xl">숫자 폰트 테스트</h3><button type="button" class="text-lg btn">123</button><button type="button" class="text-lg font-lato btn">123</button></main></div><script id="__NEXT_DATA__" type="application/json">{"props":{"pageProps":{}},"page":"/","query":{},"buildId":"eiYdyuiKcLG61JcBiroKt","nextExport":true,"autoExport":true,"isFallback":false,"scriptLoader":[]}</script></body></html>%
```

**Comment by JeongJaeSoon** [comment]
# Amazon Linux 2 package install
### git
```bash
[ec2-user@ip-172-31-40-72 ~]$ sudo yum update -y
Last metadata expiration check: 0:06:26 ago on Sat Apr  1 05:04:02 2023.
Dependencies resolved.
Nothing to do.
Complete!
[ec2-user@ip-172-31-40-72 ~]$ sudo yum install git -y
Last metadata expiration check: 0:16:38 ago on Sat Apr  1 05:04:02 2023.
Dependencies resolved.
// ...

Complete!
[ec2-user@ip-172-31-40-72 ~]$ git version
git version 2.39.2
```

### docker
```bash
[ec2-user@ip-172-31-40-72 ~]$ sudo yum install docker -y
Last metadata expiration check: 0:18:26 ago on Sat Apr  1 05:04:02 2023.
Dependencies resolved.
// ...

Complete!
[ec2-user@ip-172-31-40-72 ~]$ docker -v
Docker version 20.10.17, build 100c701
[ec2-user@ip-172-31-40-72 ~]$ sudo service docker start
Redirecting to /bin/systemctl start docker.service
[ec2-user@ip-172-31-40-72 ~]$ sudo usermod -aG docker ec2-user
[ec2-user@ip-172-31-40-72 ~]$ exit
logout
Connection to 52.79.237.25 closed.

# 94soon @ Soons-MacBookPro in ~/.ssh [14:23:43] C:126
$ ssh aws-2p3s-ec2
   ,     #_
   ~\_  ####_        Amazon Linux 2023
  ~~  \_#####\
  ~~     \###|
  ~~       \#/ ___   https://aws.amazon.com/linux/amazon-linux-2023
   ~~       V~' '->
    ~~~         /
      ~~._.   _/
         _/ _/
       _/m/'
Last login: Sat Apr  1 05:04:47 2023 from 60.158.84.117
[ec2-user@ip-172-31-40-72 ~]$ docker run hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
2db29710123e: Pull complete
Digest: sha256:ffb13da98453e0f04d33a6eee5bb8e46ee50d08ebe17735fc0779d0349e889e9
Status: Downloaded newer image for hello-world:latest

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (amd64)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/
```

**Comment by JeongJaeSoon** [comment]
# EC2 에 Manual Deploy

### Source code
```bash
[ec2-user@ip-172-31-40-72 ~]$ git clone https://github.com/2P3S/scrum-dice.git
Cloning into 'scrum-dice'...
remote: Enumerating objects: 142, done.
remote: Counting objects: 100% (142/142), done.
remote: Compressing objects: 100% (93/93), done.
remote: Total 142 (delta 51), reused 124 (delta 34), pack-reused 0
Receiving objects: 100% (142/142), 3.53 MiB | 14.86 MiB/s, done.
Resolving deltas: 100% (51/51), done.
[ec2-user@ip-172-31-40-72 ~]$ cd scrum-dice/
[ec2-user@ip-172-31-40-72 scrum-dice]$ sudo cp .env.sample /var/log/.env
[ec2-user@ip-172-31-40-72 scrum-dice]$ cp /var/log/.env .env
[ec2-user@ip-172-31-40-72 scrum-dice]$ ll -a
total 160
drwxr-xr-x. 6 ec2-user ec2-user 16384 Apr  1 05:37 .
drwx------. 4 ec2-user ec2-user   113 Apr  1 05:31 ..
-rw-r--r--. 1 ec2-user ec2-user     0 Apr  1 05:37 .env
-rw-r--r--. 1 ec2-user ec2-user     0 Apr  1 05:31 .env.sample
-rw-r--r--. 1 ec2-user ec2-user    40 Apr  1 05:31 .eslintrc.json
drwxr-xr-x. 8 ec2-user ec2-user   163 Apr  1 05:31 .git
-rw-r--r--. 1 ec2-user ec2-user   390 Apr  1 05:31 .gitignore
drwxr-xr-x. 2 ec2-user ec2-user    24 Apr  1 05:31 .husky
-rw-r--r--. 1 ec2-user ec2-user    42 Apr  1 05:31 .npmrc
-rw-r--r--. 1 ec2-user ec2-user   116 Apr  1 05:31 .prettierrc
-rw-r--r--. 1 ec2-user ec2-user   908 Apr  1 05:31 Dockerfile
-rw-r--r--. 1 ec2-user ec2-user   602 Apr  1 05:31 README.md
-rw-r--r--. 1 ec2-user ec2-user   120 Apr  1 05:31 next.config.js
-rw-r--r--. 1 ec2-user ec2-user  1096 Apr  1 05:31 package.json
-rw-r--r--. 1 ec2-user ec2-user 98505 Apr  1 05:31 pnpm-lock.yaml
-rw-r--r--. 1 ec2-user ec2-user    83 Apr  1 05:31 postcss.config.js
drwxr-xr-x. 2 ec2-user ec2-user    79 Apr  1 05:31 public
drwxr-xr-x. 5 ec2-user ec2-user    51 Apr  1 05:31 src
-rw-r--r--. 1 ec2-user ec2-user   239 Apr  1 05:31 tailwind.config.js
-rw-r--r--. 1 ec2-user ec2-user   576 Apr  1 05:31 tsconfig.json
```

### Docker
```bash
[ec2-user@ip-172-31-40-72 scrum-dice]$ DOCKER_BUILDKIT=1 docker build -t scrum-dice --secret id=npm,src=./.npmrc .
[+] Building 132.1s (21/21) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                                               0.0s
 => => transferring dockerfile: 1.01kB                                                                                                                                                             0.0s
 => [internal] load .dockerignore                                                                                                                                                                  0.1s
 => => transferring context: 2B                                                                                                                                                                    0.0s
 => [internal] load metadata for gcr.io/distroless/nodejs:16                                                                                                                                       2.4s
 => [internal] load metadata for docker.io/library/node:18.14.2-alpine                                                                                                                             2.7s
 => [build-env 1/9] FROM docker.io/library/node:18.14.2-alpine@sha256:f8a51c36b0be7434bbf867d4a08decf0100e656203d893b9b0f8b1fe9e40daea                                                             9.5s
 => => resolve docker.io/library/node:18.14.2-alpine@sha256:f8a51c36b0be7434bbf867d4a08decf0100e656203d893b9b0f8b1fe9e40daea                                                                       0.0s
 => => sha256:f8a51c36b0be7434bbf867d4a08decf0100e656203d893b9b0f8b1fe9e40daea 1.43kB / 1.43kB                                                                                                     0.0s
 => => sha256:fdbd2737cb94e25cae3db9fc5d7dc073c9675dad34239bfb3948c499a6908c19 1.16kB / 1.16kB                                                                                                     0.0s
 => => sha256:9423415aa47ab401c3f202dd56fdf379f6161a620cc51caa048887d9bdddd246 6.44kB / 6.44kB                                                                                                     0.0s
 => => sha256:63b65145d645c1250c391b2d16ebe53b3747c295ca8ba2fcb6b0cf064a4dc21c 3.37MB / 3.37MB                                                                                                     0.3s
 => => sha256:061765f30124ad9dd30397cf60c64741d3fb3b34c36f9566796687b1299183f5 47.51MB / 47.51MB                                                                                                   2.7s
 => => sha256:478140d591162fa9113c5ba76c16afafe2aa04bccd8ec45c232ffeb4f31e9c23 2.35MB / 2.35MB                                                                                                     0.6s
 => => extracting sha256:63b65145d645c1250c391b2d16ebe53b3747c295ca8ba2fcb6b0cf064a4dc21c                                                                                                          0.2s
 => => sha256:00ca3aba45c3a9811387d943d26291284ca6f938036760fcf85dbb2ab78e496a 450B / 450B                                                                                                         0.8s
 => => extracting sha256:061765f30124ad9dd30397cf60c64741d3fb3b34c36f9566796687b1299183f5                                                                                                          5.7s
 => => extracting sha256:478140d591162fa9113c5ba76c16afafe2aa04bccd8ec45c232ffeb4f31e9c23                                                                                                          0.4s
 => => extracting sha256:00ca3aba45c3a9811387d943d26291284ca6f938036760fcf85dbb2ab78e496a                                                                                                          0.0s
 => [internal] load build context                                                                                                                                                                  0.1s
 => => transferring context: 3.88MB                                                                                                                                                                0.1s
 => [stage-1 1/6] FROM gcr.io/distroless/nodejs:16@sha256:0f7fbe2f3853fd719204ff417dda421eea2f8db8e17875820fddac5d3a8f572c                                                                        10.7s
 => => resolve gcr.io/distroless/nodejs:16@sha256:0f7fbe2f3853fd719204ff417dda421eea2f8db8e17875820fddac5d3a8f572c                                                                                 0.0s
 => => sha256:0f7fbe2f3853fd719204ff417dda421eea2f8db8e17875820fddac5d3a8f572c 741B / 741B                                                                                                         0.0s
 => => sha256:dd935e4985065176e806932474759ee82ad580f649cf7fe791632c5bbc1766ca 918B / 918B                                                                                                         0.0s
 => => sha256:a5a8ba5ebae9ff6a68d4897ad0b52ea1585ac8b2b53ede7607867cfb3edc9ed8 967B / 967B                                                                                                         0.0s
 => => sha256:383e1c5dd0c1830143b1230e90292ebd4219911e0512b70d250c8907c4899110 821.00kB / 821.00kB                                                                                                 1.3s
 => => sha256:c59673e9fae3f9d588110a25acdf7240f3a5d97c40fb86ccc71c23bf7abbea53 8.02MB / 8.02MB                                                                                                     4.3s
 => => extracting sha256:383e1c5dd0c1830143b1230e90292ebd4219911e0512b70d250c8907c4899110                                                                                                          0.6s
 => => sha256:7dcffaf987694bb0a0863ae2c3b582125b1c20d3148f0412f901b918b9a8e22d 817.61kB / 817.61kB                                                                                                 1.7s
 => => sha256:9cec46870c178ccc4225033fe98f8b6de5bbb8b01a0ead80ac97acc076605424 32.00MB / 32.00MB                                                                                                   4.2s
 => => extracting sha256:c59673e9fae3f9d588110a25acdf7240f3a5d97c40fb86ccc71c23bf7abbea53                                                                                                          1.3s
 => => extracting sha256:7dcffaf987694bb0a0863ae2c3b582125b1c20d3148f0412f901b918b9a8e22d                                                                                                          0.4s
 => => extracting sha256:9cec46870c178ccc4225033fe98f8b6de5bbb8b01a0ead80ac97acc076605424                                                                                                          4.1s
 => [build-env 2/9] WORKDIR /app                                                                                                                                                                   0.1s
 => [build-env 3/9] RUN npm install --location=global pnpm@7                                                                                                                                       3.6s
 => [stage-1 2/6] WORKDIR /app                                                                                                                                                                     0.1s
 => [build-env 4/9] COPY .npmrc ./                                                                                                                                                                 0.0s
 => [build-env 5/9] COPY package.json ./                                                                                                                                                           0.1s
 => [build-env 6/9] COPY pnpm-lock.yaml ./                                                                                                                                                         0.0s
 => [build-env 7/9] RUN --mount=type=secret,id=npm,target=/app/.npmrc pnpm install --frozen-lockfile                                                                                              31.7s
 => [build-env 8/9] COPY . /app                                                                                                                                                                    0.2s
 => [build-env 9/9] RUN pnpm run build                                                                                                                                                            46.5s
 => [stage-1 3/6] COPY --chown=nonroot:nonroot --from=build-env /app/next.config.js ./                                                                                                             0.1s
 => [stage-1 4/6] COPY --chown=nonroot:nonroot --from=build-env /app/public ./public                                                                                                               0.0s
 => [stage-1 5/6] COPY --chown=nonroot:nonroot --from=build-env /app/.next ./.next                                                                                                                 0.2s
 => [stage-1 6/6] COPY --chown=nonroot:nonroot --from=build-env /app/node_modules ./node_modules                                                                                                   3.9s
 => exporting to image                                                                                                                                                                            16.6s
 => => exporting layers                                                                                                                                                                           16.6s
 => => writing image sha256:b0ff4f1d898f9fcb92b8240497dd4e3e22d43af5889f85e265898f7236c8db3e                                                                                                       0.0s
 => => naming to docker.io/library/scrum-dice                                                                                                                                                      0.0s
[ec2-user@ip-172-31-40-72 scrum-dice]$ docker run --env-file=.env --rm --name scrum-dice -p 80:3000 -d scrum-dice
da47ec693606cc401d3a07722eb5c42125b1f11e38482b2b69fa91f639e40538
```

### Check
* EC2
  ```
  [ec2-user@ip-172-31-40-72 scrum-dice]$ curl localhost
  <!DOCTYPE html><html lang="kr"><head><meta charSet="utf-8"/><title>Create Next App</title><meta name="description" content="Generated by create next app"/><meta name="viewport" content="width=device-width, initial-scale=1"/><link rel="icon" href="/favicon.ico"/><meta name="next-head-count" content="5"/><link rel="preload" href="/_next/static/media/7b53eb385565b6db-s.p.woff2" as="font" type="font/woff2" crossorigin="anonymous" data-next-font="size-adjust"/><link rel="preload" href="/_next/static/media/28777f2d837b799c-s.p.woff2" as="font" type="font/woff2" crossorigin="anonymous" data-next-font="size-adjust"/><link rel="preload" href="/_next/static/media/400b60eed27dfb33-s.p.woff2" as="font" type="font/woff2" crossorigin="anonymous" data-next-font="size-adjust"/><link rel="preload" href="/_next/static/media/7bb39e817a36d930-s.p.woff2" as="font" type="font/woff2" crossorigin="anonymous" data-next-font="size-adjust"/><link rel="preload" href="/_next/static/css/3ad7adcd6ac0cdb4.css" as="style"/><link rel="stylesheet" href="/_next/static/css/3ad7adcd6ac0cdb4.css" data-n-g=""/><link rel="preload" href="/_next/static/css/cbe848909a7e60de.css" as="style"/><link rel="stylesheet" href="/_next/static/css/cbe848909a7e60de.css" data-n-p=""/><link rel="preload" href="/_next/static/css/268f21f1b6a953c1.css" as="style"/><link rel="stylesheet" href="/_next/static/css/268f21f1b6a953c1.css" data-n-p=""/><noscript data-n-css=""></noscript><script defer="" nomodule="" src="/_next/static/chunks/polyfills-c67a75d1b6f99dc8.js"></script><script src="/_next/static/chunks/webpack-0c2b03d183be1d16.js" defer=""></script><script src="/_next/static/chunks/framework-ac88a2a245aea9ab.js" defer=""></script><script src="/_next/static/chunks/main-dd3f6ca723899de0.js" defer=""></script><script src="/_next/static/chunks/pages/_app-5badd0c9e455f14e.js" defer=""></script><script src="/_next/static/chunks/pages/index-cee06aa099f65162.js" defer=""></script><script src="/_next/static/86h90gCBR95-_OJGfyJYn/_buildManifest.js" defer=""></script><script src="/_next/static/86h90gCBR95-_OJGfyJYn/_ssgManifest.js" defer=""></script></head><body><div id="__next"><main class="__className_a1b27a __variable_9ec5dd"><h3 class="text-3xl">다국어 폰트 테스트</h3><button type="button" class="btn">한국어 폰트 테스트</button><button type="button" class="font-lato btn">english font test</button><h3 class="text-3xl">숫자 폰트 테스트</h3><button type="button" class="text-lg btn">123</button><button type="button" class="text-lg font-lato btn">123</button></main></div><script id="__NEXT_DATA__" type="application/json">{"props":{"pageProps":{}},"page":"/","query":{},"buildId":"86h90gCBR95-_OJGfyJYn","nextExport":true,"autoExport":true,"isFallback":false,"scriptLoader":[]}</script></body></html>
  ```
* Local : 52.79.237.25
  ```bash
  $ curl 52.79.237.25
  <!DOCTYPE html><html lang="kr"><head><meta charSet="utf-8"/><title>Create Next App</title><meta name="description" content="Generated by create next app"/><meta name="viewport" content="width=device-width, initial-scale=1"/><link rel="icon" href="/favicon.ico"/><meta name="next-head-count" content="5"/><link rel="preload" href="/_next/static/media/7b53eb385565b6db-s.p.woff2" as="font" type="font/woff2" crossorigin="anonymous" data-next-font="size-adjust"/><link rel="preload" href="/_next/static/media/28777f2d837b799c-s.p.woff2" as="font" type="font/woff2" crossorigin="anonymous" data-next-font="size-adjust"/><link rel="preload" href="/_next/static/media/400b60eed27dfb33-s.p.woff2" as="font" type="font/woff2" crossorigin="anonymous" data-next-font="size-adjust"/><link rel="preload" href="/_next/static/media/7bb39e817a36d930-s.p.woff2" as="font" type="font/woff2" crossorigin="anonymous" data-next-font="size-adjust"/><link rel="preload" href="/_next/static/css/3ad7adcd6ac0cdb4.css" as="style"/><link rel="stylesheet" href="/_next/static/css/3ad7adcd6ac0cdb4.css" data-n-g=""/><link rel="preload" href="/_next/static/css/cbe848909a7e60de.css" as="style"/><link rel="stylesheet" href="/_next/static/css/cbe848909a7e60de.css" data-n-p=""/><link rel="preload" href="/_next/static/css/268f21f1b6a953c1.css" as="style"/><link rel="stylesheet" href="/_next/static/css/268f21f1b6a953c1.css" data-n-p=""/><noscript data-n-css=""></noscript><script defer="" nomodule="" src="/_next/static/chunks/polyfills-c67a75d1b6f99dc8.js"></script><script src="/_next/static/chunks/webpack-0c2b03d183be1d16.js" defer=""></script><script src="/_next/static/chunks/framework-ac88a2a245aea9ab.js" defer=""></script><script src="/_next/static/chunks/main-dd3f6ca723899de0.js" defer=""></script><script src="/_next/static/chunks/pages/_app-5badd0c9e455f14e.js" defer=""></script><script src="/_next/static/chunks/pages/index-cee06aa099f65162.js" defer=""></script><script src="/_next/static/86h90gCBR95-_OJGfyJYn/_buildManifest.js" defer=""></script><script src="/_next/static/86h90gCBR95-_OJGfyJYn/_ssgManifest.js" defer=""></script></head><body><div id="__next"><main class="__className_a1b27a __variable_9ec5dd"><h3 class="text-3xl">다국어 폰트 테스트</h3><button type="button" class="btn">한국어 폰트 테스트</button><button type="button" class="font-lato btn">english font test</button><h3 class="text-3xl">숫자 폰트 테스트</h3><button type="button" class="text-lg btn">123</button><button type="button" class="text-lg font-lato btn">123</button></main></div><script id="__NEXT_DATA__" type="application/json">{"props":{"pageProps":{}},"page":"/","query":{},"buildId":"86h90gCBR95-_OJGfyJYn","nextExport":true,"autoExport":true,"isFallback":false,"scriptLoader":[]}</script></body></html>%
  ```

**Comment by JeongJaeSoon** [comment]
URL
http://43.201.27.194/
