### ISSUE TITLE
scrum-dice 가 EC2 에 Auto deploy 된다.

### ISSUE THREAD

**Issue by JeongJaeSoon** [2P3S/scrum-dice#21]
### 현상황
* #1 에서 docker deploy 작업 완료
* Codepipeline 을 사용한 자동 배포 작업을 진행
  * 참고자료 1 : [Tistory blog](https://dev-jaesoon.tistory.com/entry/GitHub-%EC%97%90%EC%84%9C-EC2-%EB%A1%9C-%EC%9E%90%EB%8F%99-%EB%B0%B0%ED%8F%ACCD-%ED%95%98%EA%B8%B0-AWS)
  * 참고자료 2 : [AWS doc](https://docs.aws.amazon.com/codedeploy/latest/userguide/codedeploy-agent-operations-install-linux.html)
* https://github.com/aws/aws-codedeploy-agent/issues/355
  * AL2 2023 에서는 ruby version 의존성 문제로 codedeploy-agent 를 제대로 지원하지 않는 문제가 있음
  * Error log
    ```bash
    [ec2-user@ip-172-31-40-72 ~]$ sudo yum install ruby
    Last metadata expiration check: 1:16:08 ago on Sat Apr  1 05:04:02 2023.
    Package ruby3.2-3.2.1-179.amzn2023.0.1.x86_64 is already installed.
    Dependencies resolved.
    Nothing to do.
    Complete!
    [ec2-user@ip-172-31-40-72 ~]$ wget https://aws-codedeploy-ap-northeast-2.s3.ap-northeast-2.amazonaws.com/latest/install
    --2023-04-01 06:20:18--  https://aws-codedeploy-ap-northeast-2.s3.ap-northeast-2.amazonaws.com/latest/install
    Resolving aws-codedeploy-ap-northeast-2.s3.ap-northeast-2.amazonaws.com (aws-codedeploy-ap-northeast-2.s3.ap-northeast-2.amazonaws.com)... 52.219.202.50
    Connecting to aws-codedeploy-ap-northeast-2.s3.ap-northeast-2.amazonaws.com (aws-codedeploy-ap-northeast-2.s3.ap-northeast-2.amazonaws.com)|52.219.202.50|:443... connected.
    HTTP request sent, awaiting response... 200 OK
    Length: 17845 (17K) []
    Saving to: ‘install’
    
    install                                           100%[=============================================================================================================>]  17.43K  --.-KB/s    in 0s
    
    2023-04-01 06:20:18 (161 MB/s) - ‘install’ saved [17845/17845]
    
    [ec2-user@ip-172-31-40-72 ~]$ chmod +x ./install
    [ec2-user@ip-172-31-40-72 ~]$ sudo ./install auto
    /usr/share/ruby3.2/logger/log_device.rb:83:in `exist?': no implicit conversion of Array into String (TypeError)
    
              if File.exist?(path)
                             ^^^^
    	from /usr/share/ruby3.2/logger/log_device.rb:83:in `set_dev'
    	from /usr/share/ruby3.2/logger/log_device.rb:18:in `initialize'
    	from /usr/share/ruby3.2/logger.rb:587:in `new'
    	from /usr/share/ruby3.2/logger.rb:587:in `initialize'
    	from ./install:43:in `new'
    	from ./install:43:in `<main>'
    ```
* Issues 가 해결되기 전까지, 수동으로 배포를 진행

### Todo
* Application 
  * [x] appspec.yml 작성
* AWS
  * [x] CodePiepline
  * [x] S3
  * [x] EC2 
  * [x] discord webhook notification
* [ ] Issue 가 해결되면 Auto deploy 의 작동을 확인

**Comment by JeongJaeSoon** [comment]
# CodePipeline 설정 완료

![Image](https://user-images.githubusercontent.com/53788601/229362829-a524a546-143c-4fc6-b539-d9402718578d.png)

→ codedeploy-agent 미설치로 실패

**Comment by JeongJaeSoon** [comment]
Discord notifications 는 Slack ChatBot notifications 를 경유한 Web hook 으로 대체
* CodePipeline 이 직접 Discord notifications 하기 위해서는 lambda 의 구현이 필요
* 구현, 실행 코스트 대비 그렇게 필요성이 높지 않음

**Comment by JeongJaeSoon** [comment]
# codedeploy-agent 의 Issues 대응이 끝났기 때문에, 재설치 시도
```bash
[ec2-user@ip-172-31-40-72 ~]$ rm -rf install
[ec2-user@ip-172-31-40-72 ~]$ wget https://aws-codedeploy-ap-northeast-2.s3.ap-northeast-2.amazonaws.com/latest/install
--2023-04-10 15:24:50--  https://aws-codedeploy-ap-northeast-2.s3.ap-northeast-2.amazonaws.com/latest/install
Resolving aws-codedeploy-ap-northeast-2.s3.ap-northeast-2.amazonaws.com (aws-codedeploy-ap-northeast-2.s3.ap-northeast-2.amazonaws.com)... 52.219.206.34
Connecting to aws-codedeploy-ap-northeast-2.s3.ap-northeast-2.amazonaws.com (aws-codedeploy-ap-northeast-2.s3.ap-northeast-2.amazonaws.com)|52.219.206.34|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 17892 (17K) []
Saving to: ‘install’

install                                                     100%[=========================================================================================================================================>]  17.47K  --.-KB/s    in 0.001s

2023-04-10 15:24:50 (12.9 MB/s) - ‘install’ saved [17892/17892]

[ec2-user@ip-172-31-40-72 ~]$ chmod +x ./install
[ec2-user@ip-172-31-40-72 ~]$ sudo ./install auto
I, [2023-04-10T15:25:07.350910 #431849]  INFO -- : Starting Ruby version check.
I, [2023-04-10T15:25:07.351362 #431849]  INFO -- : Starting update check.
I, [2023-04-10T15:25:07.351472 #431849]  INFO -- : Attempting to automatically detect supported package manager type for system...
I, [2023-04-10T15:25:07.365452 #431849]  INFO -- : Checking AWS_REGION environment variable for region information...
I, [2023-04-10T15:25:07.365587 #431849]  INFO -- : Checking EC2 metadata service for region information...
I, [2023-04-10T15:25:07.396620 #431849]  INFO -- : Checking AWS_DOMAIN environment variable for domain information...
I, [2023-04-10T15:25:07.396748 #431849]  INFO -- : Checking EC2 metadata service for domain information...
I, [2023-04-10T15:25:07.404517 #431849]  INFO -- : Downloading version file from bucket aws-codedeploy-ap-northeast-2 and key latest/LATEST_VERSION...
I, [2023-04-10T15:25:07.404763 #431849]  INFO -- : Endpoint: https://aws-codedeploy-ap-northeast-2.s3.ap-northeast-2.amazonaws.com/latest/LATEST_VERSION
I, [2023-04-10T15:25:07.562605 #431849]  INFO -- : Downloading package from bucket aws-codedeploy-ap-northeast-2 and key releases/codedeploy-agent-1.6.0-49.noarch.rpm...
I, [2023-04-10T15:25:07.562884 #431849]  INFO -- : Endpoint: https://aws-codedeploy-ap-northeast-2.s3.ap-northeast-2.amazonaws.com/releases/codedeploy-agent-1.6.0-49.noarch.rpm
I, [2023-04-10T15:25:07.655641 #431849]  INFO -- : Executing `/usr/bin/yum -y localinstall /tmp/codedeploy-agent-1.6.0-49.noarch.tmp-20230410-431849-8vk7w5.rpm`...
Amazon Linux 2023 repository                                                                                                                                                                                   29 kB/s | 3.6 kB     00:00
Amazon Linux 2023 Kernel Livepatch repository                                                                                                                                                                  20 kB/s | 2.6 kB     00:00
Dependencies resolved.
==============================================================================================================================================================================================================================================
 Package                                                        Architecture                                         Version                                                 Repository                                                  Size
==============================================================================================================================================================================================================================================
Installing:
 codedeploy-agent                                               noarch                                               1.6.0-49                                                @commandline                                               2.7 M

Transaction Summary
==============================================================================================================================================================================================================================================
Install  1 Package

Total size: 2.7 M
Installed size: 13 M
Downloading Packages:
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                                                                                                      1/1
  Running scriptlet: codedeploy-agent-1.6.0-49.noarch                                                                                                                                                                                     1/1

pre hook : 1
Checking if there is already a process named codedeploy-agent running.

  Installing       : codedeploy-agent-1.6.0-49.noarch                                                                                                                                                                                     1/1
  Running scriptlet: codedeploy-agent-1.6.0-49.noarch                                                                                                                                                                                     1/1

post hook : 1
Check if there is a codedeployagent config file.
Start codedeploy-agent in post hook if this is a first install.

  Verifying        : codedeploy-agent-1.6.0-49.noarch                                                                                                                                                                                     1/1
==============================================================================================================================================================================================================================================
WARNING:
  A newer release of "Amazon Linux" is available.

  Available Versions:

  Version 2023.0.20230329:
    Run the following command to upgrade to 2023.0.20230329:

      dnf upgrade --releasever=2023.0.20230329

    Release notes:
     https://docs.aws.amazon.com/linux/al2023/release-notes/relnotes.html

==============================================================================================================================================================================================================================================

Installed:
  codedeploy-agent-1.6.0-49.noarch

Complete!
I, [2023-04-10T15:25:12.535090 #431849]  INFO -- : Update check complete.
I, [2023-04-10T15:25:12.535244 #431849]  INFO -- : Stopping updater.
[ec2-user@ip-172-31-40-72 ~]$ sudo service codedeploy-agent status
/opt/codedeploy-agent/vendor/gems/gli-2.11.0/lib/gli/commands/help_modules/global_help_format.rb:37: warning: Passing safe_level with the 2nd argument of ERB.new is deprecated. Do not use it, and specify other arguments as keyword arguments.
/opt/codedeploy-agent/vendor/gems/gli-2.11.0/lib/gli/commands/help_modules/global_help_format.rb:37: warning: Passing trim_mode with the 3rd argument of ERB.new is deprecated. Use keyword argument like ERB.new(str, trim_mode: ...) instead.
/opt/codedeploy-agent/vendor/gems/gli-2.11.0/lib/gli/commands/help_modules/command_help_format.rb:27: warning: Passing safe_level with the 2nd argument of ERB.new is deprecated. Do not use it, and specify other arguments as keyword arguments.
/opt/codedeploy-agent/vendor/gems/gli-2.11.0/lib/gli/commands/help_modules/command_help_format.rb:27: warning: Passing trim_mode with the 3rd argument of ERB.new is deprecated. Use keyword argument like ERB.new(str, trim_mode: ...) instead.
The AWS CodeDeploy agent is running as PID 431988
```
