### ISSUE TITLE
ElastiCache for Redis 생성 및 접속 확인

### ISSUE THREAD

**Issue by JeongJaeSoon** [2P3S/scrum-dice#4]
### ToDo

- [x] Elastic Cache for Redis 생성
- [x] Private Subnet 설정
- [x] EC2 에서 `redis-cli` 로 접속 성공여부 확인

**Comment by JeongJaeSoon** [comment]
```bash
[ec2-user@ip-172-31-40-72 redis-stable]$ redis-cli -h dev-2p3s-redis.svn1li.ng.0001.apn2.cache.amazonaws.com -p 6379
dev-2p3s-redis.svn1li.ng.0001.apn2.cache.amazonaws.com:6379>
```
