### ISSUE TITLE
socket.io-client를 활용한 플래닝 포커 방 입장 로직 작성

### ISSUE THREAD

**Issue by hyunnnn98** [2P3S/scrum-dice#71]
# Todo

- [x] socket.emit / join-room
- [x] socket.on / join-success
- [x] socket.on / failure
- [x] localStorage /  [GET, SET] member object
